### ISSUE TITLE
Example processing?

### ISSUE THREAD

**Issue by justinmchase** [dyedgreen/clay#1]
Can you give an example of how you process the results? As in how you actually execute your logic based on these parse results?

I do like that this is both simple and supports subcommands.

**Comment by dyedgreen** [comment]
You get back an object which you can then pass into some function / read values from in any way you like.

This architecture makes your applications easy to test, since it separates processing from inputs.

eg:
```JavaScript
import { Command, string } from "https://deno.land/x/clay/mod.ts";

const cmd = new Command("a Hello world.")
  .required(string, "name", { flags: ["n", "name"], description: "The name." });

const { name } = cmd.run();
console.log(`Hello ${name}`);
```

**Comment by justinmchase** [comment]
Ok but it's a lot harder when you have sub commands. Typically for a command you want to have something that essentially resolves your input to a function that knows how to process that function.

One way I've seen this in other libraries is to literally add a handler function to the command... but that's not strictly necessary, the other way to do it would to just provide a resolver or even just an enum or string that could be used to easily map to the right function.

So for example:
```ts
import {
  Command,
  CommandGroup,
} from "https://deno.land/x/clay/mod.ts"

const a = new Command("a")
const b = new Command("b")
const c = new Command("c")
const d = new Command("d")

const g1 = new CommandGroup("one")
  .subcommand("a", a)
  .subcommand("b", b)

const g2 = new CommandGroup("two")
  .subcommand("c", c)
  .subcommand("d", d)

const cli = new CommandGroup("commands")
  .subcommand("one")
  .subcommand("two")

console.log(cli.run()); // ??
```

So now suppose the user enters the command `example one a` that will give me the object:
```js
{ one: { a: {} } }
```

And now I have to route this to a function that knows how to process the `a` command, the question is how? Following your pattern there...

```ts
const { one, two } = cmd.run()
if (one) {
  const { a, b } = one
  if (a) {
    await aHandler(a)
  } else if (b) {
    await bHandler(b)
  }
} else if (two) {
  const { c, d } = two
  if (c) {
    await cHandler(c)
  } else if (d) {
    await dHandler(d)
  }
}
```

And so this is pretty ugly... What if I have dozens of commands that can go as deep as 4 levels?

So there is a couple of things that could probably be done, here are a couple possibilities:

```ts
const a = new Command("a", { handler: aHandler })
```

Put the handler right in the command, have the run function either invoke it or maybe return it on the final object:
```ts
console.log(cli.run()) // { one: { a: {} }, __meta: { handler: [Function] } }
```

Or maybe provide a mapping function which takes an object with the same structure as the return and essentially does the above if/else logic but in a generic way, something like:

```ts
import {
  Command,
  CommandGroup,
  Router,
} from "https://deno.land/x/clay/mod.ts"

const handlers = {
  one: {
    a: aHandler,
    b: bHandler,
  },
  two: {
    c: cHandler,
    d: dHandler,
  }
}
const cli = new CommandGroup(...)
const router = new Router(handlers)
await router.run(cli.run())
```

Another way would be to change the structure of the output object to just make routing with a switch statement a little easier...

```ts
const { __key, one, two } = cmd.run()
switch (__key) {
  case 'one':
    const { __key: oneKey, a, b } = one
    switch (oneKey) {
      case 'a':
        return await aHandler(a)
      case 'b':
        return await bHandler(b)
    }
  case 'two':
    const { __key: twoKey, c, d } = two
    switch (twoKey) {
      case 'c':
        return await cHandler(c)
      case 'd':
        return await dHandler(d)
  }
}
```

Just some thoughts on how to help make this a bit easier to use.

But I do think you're on a good path, Yargs and Commander are so frickin complicated and support so much stuff that it ends up being kind of overy complicated to use and can have issues simply because it supports _too_ much stuff and the command/sub-command features feel like bolt-ons. For example with commander you can put a handler on the _command group_ as well as the command which then the command group handler is never invoked... _unless_ you do some other complicated stuff. Its just awful. This model you have here is pretty clear and the way it probably should be. Good luck.
